spring:
  r2dbc:
    pool:
      initial-size: 1
      max-size: 3
      max-idle-time: 30s
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  sql:
    init:
      mode: always

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}
    publisher-confirm-type: correlated
    publisher-returns: true

  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
      timeout: 2000ms

    cache:
      type: redis
      redis:
        time-to-live: 600000
        cache-null-values: false